services:
  - type: web
    name: tts-pro
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn -b :$PORT tts:flask_app --threads 2 & \
      streamlit run tts.py --server.port $PORT --server.headless=true
    envVars:
      - key: PORT
        value: 10000
