services:
  - type: web
    name: tts-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      gunicorn -b :$PORT app:flask_app & \
      streamlit run app.py --server.port $PORT --server.headless=true
    envVars:
      - key: PORT
        value: 10000
