services:
  - type: web
    name: tts-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      gunicorn -b :$PORT app:flask_app & \
      python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_APP
        value: app.py
